# Generated by Django 5.2.1 on 2025-05-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('used_books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedbook',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/'),
        ),
    ]
