# Generated by Django 5.2.1 on 2025-06-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_cafeteriamenu_menuphoto_delete_lunchmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='worklog',
            name='hours_worked',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
